#!/bin/sh

. /etc/functions.sh
. /lib/functions/commotion.sh

[ ! -f /etc/config/wireless ] && wifi detect > /etc/config/wireless

commotion_set_nodeid_from_mac $(uci get wireless.@wifi-device[0].macaddr)
uci_set commotiond @node[0] id $(commotion_get_nodeid)
uci_commit commotiond

if [ -f /etc/commotion/profiles.d/commotionMesh ]; then

uci_set wireless @wifi-device[0] disabled 0
uci_set wireless @wifi-device[0] channel 11 
uci_remove wireless @wifi-iface[0]
uci_add wireless wifi-iface commotionMesh
uci_set wireless commotionMesh device radio0
uci_set wireless commotionMesh mode adhoc
uci_set wireless commotionMesh ssid "commotionwireless.net"
uci_set wireless commotionMesh encryption "psk2"
uci_set wireless commotionMesh key "password"
uci_add wireless wifi-iface commotionAP
uci_set wireless commotionAP device radio0
uci_set wireless commotionAP mode ap
uci_set wireless commotionAP network lan
uci_set wireless commotionAP ssid "Setup"
uci_commit wireless

/etc/init.d/commotion restart
/etc/init.d/network restart

fi

exit 0
